version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  # dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  shortie:
    image: shortie
    restart: always
    ports:
      - 8080:4000
    links:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}