version: '3'

services:

  proxy:
    image: jwilder/nginx-proxy
    network_mode: bridge
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker-postgres/db/data:/var/lib/postgresql/data

  shortie:
    image: shortie
    restart: always
    ports:
      - 8080:4000
    depends_on:
      - db
      - proxy
    links:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      VIRTUAL_HOST: short.ie
      VIRTUAL_PORT: 4000
